# Generated by Django 4.0.2 on 2022-02-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=125, verbose_name='Имя товара')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('file', models.FileField(upload_to='delivery', verbose_name='Файл')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Наименование типа')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Наимнование адриса')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery', verbose_name='Множественных Адресов Указанных Выдачи')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='product_type',
            field=models.ManyToManyField(to='delivery.ProductType', verbose_name='Тип товака'),
        ),
    ]
